- name: 下载在线安装包
  copy:
      dest: /root
      src: "{{ version }}/{{ fileName }}"

- name: 解压
  unarchive:
      src: /root/{{ fileName }} # required. If C(remote_src=no) (default), local path to archive file to copy to the target server; can be absolute or relative. If C(remote_src=yes), path on the target server to existing archive file to unpack.,If C(remote_src=yes) and C(src) contains C(://), the remote machine will download the file from the URL first. (version_added 2.0). This is only for simple cases, for full download support use the M(get_url) module.
      dest: /root # required. Remote absolute path where the archive should be unpacked.

- name: 设置环境变量
  lineinfile:
      path: ~/.bashrc
      line: PATH=$PATH:/root/{{ folderName }}

- name: 使环境变量生效
  shell: source ~/.bashrc

- name: 开启dfdaemon
  shell: nohup df-daemon --registry http://10.0.13.19 &