- name: copy files
  copy:
      dest: /root # required. Remote absolute path where the file should be copied to. If I(src) is a directory, this must be a directory too. If I(dest) is a nonexistent path and if either I(dest) ends with "/" or I(src) is a directory, I(dest) is created. If I(src) and I(dest) are files, the parent directory of I(dest) isn't created: the task fails if it doesn't already exist.
      src: {{ item }} # not required. Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to Rsync.
  with_items:
    - bigimage.sh
    - tensorflow.sh

- name: chmod
  shell: chmod +x /root/bigimage.sh; chmod +x /root/tensorflow.sh

- name: docker pull
  shell: /root/{{ file }}